# Generated by Django 2.2 on 2021-08-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_auto_20210819_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='id',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
