# Generated by Django 2.2 on 2021-08-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0003_auto_20210822_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='movimiento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
