# Generated by Django 2.2 on 2021-08-22 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0006_auto_20210822_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='movimiento',
            field=models.CharField(blank=True, default=datetime.datetime(2021, 8, 22, 22, 29, 2, 987641, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
