# Generated by Django 2.2 on 2021-08-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0011_auto_20210822_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='movimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
