# Generated by Django 2.2 on 2021-09-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0017_auto_20210926_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='cinci',
        ),
    ]
