# Generated by Django 2.2 on 2021-09-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0019_cargo_cinci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='cuenta',
            new_name='cuenta_c',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cinci',
            field=models.ForeignKey(blank=True, db_column='cuenta', null=True, on_delete=django.db.models.deletion.CASCADE, to='count.Cincuenta'),
        ),
    ]
