# Generated by Django 2.2 on 2021-09-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0020_auto_20210926_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='nombre',
            new_name='nombre_c',
        ),
    ]
