# Generated by Django 2.2 on 2021-09-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0022_remove_cargo_cinci'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cuenta_cin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
